version: 0.0
os: linux

files:
  - source: /  # Copy everything from the root of the artifact
    destination: /var/www/html  # The folder Nginx uses to serve static files

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh  # Install Nginx or Apache
    - runas: root

  ApplicationStart:
    - location: scripts/start_server.sh  # Start the server (e.g., Nginx)
    - runas: root

  ValidateService:
    - location: scripts/validate.sh  # Optionally validate if the app is running
    - runas: root
