version: 0.0
os: linux

files:
  - source: /  # Copy everything from the root of the artifact
    destination: /usr/share/index/  # The folder Nginx uses to serve static files

hooks:
  AfterInstall:
    - location: shellscripts/install_dependencies.sh  # Install Nginx or Apache
    - runas: root

  ApplicationStart:
    - location: shellscripts/start_server.sh  # Start the server (e.g., Nginx)
    - runas: root
