version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js and dependencies..."
      - curl -sL https://rpm.nodesource.com/setup_22.x | bash -  # Replace '16.x' with your desired Node.js version
      - yum install -y nodejs
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - npm install  # Install dependencies
  build:
    commands:
      - echo "Building the React app..."
      - npm run build  # Build the production-ready React app
  post_build:
    commands:
      - echo "Copying build artifacts to S3 bucket..."
      - aws s3 cp build/ s3://travelreactapp-awscicd/ --recursive  # Upload the build folder to the S3 bucket

artifacts:
  files:
    - '**/*'  # Include all files
  base-directory: build  # The build directory created by React
