version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "Installing Node.js and dependencies..."
      - npm install
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - echo "Building the React app..."
      - npm run build  # Build the production-ready React app
  post_build:
    commands:
      - echo "Copying build artifacts to S3 bucket..."

artifacts:
  files:
    - '**/*'  # Include all files
    - '../appspec.yml'
    - '../scripts/**'
  base-directory: build  # The build directory created by React
  discard-paths: no
